name: Publish docker image
on:
  push:
    branches:
      - main
jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: rg.fr-par.scw.cloud/evilmeow
          username: does_not_matter
          password: ${{ secrets.EVILMEOW_REGISTRY_TOKEN }}
      - run: echo "Publishing image"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Pushing image
        run: make push
